<?php
/**
 * @file
 * Code for the Pocket feature.
 */

include_once 'com_pocket.features.inc';

/*
* Implements hook_node_view()
*/
function com_pocket_node_view($node, $view_mode) {
      $type = $node->type;

      $later_types = array_filter(variable_get('com_pocket_link_later_node_types', array()));
      if (in_array($type, $later_types)){
          $links['pocket']['pocket_save'] = array(
          'title' => t("Read Later"),
          'attributes' => array('title' => t("Read Later")),
        );
      }
      

      $share_types = array_filter(variable_get('com_pocket_link_share_node_types', array()));
      if(in_array($type, $share_types)){
          $links['pocket']['pocket_share'] = array(
          'title' => t("Share"),
          'href' => 'eform/submit/suggest_content?field_suggested_content='.$node->nid.'&field_suggest_user_sending='.$node->uid,
          'attributes' => array('title' => t("Share")),
        );
      }
      

      $node->content['links']['pocket'] = array(
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline')),
      );
}

/**
 * Implements hook_menu().
 */
function com_pocket_menu() {
  $items['admin/config/pocket'] = array(
    'title'            => 'Pocket settings',
    'description'      => 'Pocket settings.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('com_pocket_admin_settings'),
    'file'             => 'com_pocket.admin.inc',
    'access callback' => TRUE,
    'type'             => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
* Implementation of hook_simpletest().
*/
function com_pocket_simpletest() {
	$dir = drupal_get_path('module', 'com_pocket') .'/tests';
	$tests = file_scan_directory($dir, '\.test$');
	return array_keys($tests);

}
