<?php
/**
 * @file
 * Code for the Pocket feature.
 */

include_once 'com_pocket.features.inc';

/*
* Implements hook_node_view()
*/
function com_pocket_node_view($node, $view_mode) {
      dpm($node);
      $links['pocket_save'] = array(
        'title' => t("Read Later"),
        'attributes' => array('title' => t("Read Later")),
      );

        $links['pocket_share'] = array(
        'title' => t("Share"),
        'href' => 'eform/submit/suggest_content?field_suggested_content='.$node->nid.'&field_suggest_user_sending='.$node->uid,
        'attributes' => array('title' => t("Share")),
      );

      $node->content['links']['pocket'] = array(
        '#links' => $links,
        '#attributes' => array('class' => array('links', 'inline')),
      );
}

/**
* Implementation of hook_simpletest().
*/
function com_pocket_simpletest() {
	$dir = drupal_get_path('module', 'com_pocket') .'/tests';
	$tests = file_scan_directory($dir, '\.test$');
	return array_keys($tests);

}
