<?php

/**
 * Implements hook_node_insert().
 */
function notification_center_node_insert($node) {

}

/**
 * Implements hook_comment_insert().
 */
function notification_center_comment_insert($comment) {

}

/**
 * Implements hook_flag_flag().
 */
function notification_center_flag_flag($flag, $entity_id, $account, $flagging) {

}

/**
 * Implements hook_flag_unflag().
 */
function notification_center_flag_unflag($flag, $entity_id, $account, $flagging) {

}